# -*- coding: utf-8 -*-
"""A1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ojBTyEdUh0XVBxlGpSnld6oy89yOZLi

# A company wants to identify whether an employee is eligible for a bonus based on attendance percentage and performance rating
"""

attendance_percentage = float(input("Enter employee's attendance percentage: "))
performance_rating = float(input("Enter employee's performance rating: "))

if attendance_percentage >= 75 and performance_rating >= 4:
  print("Employee is eligible for bonus.")
else:
  print("Employee is not eligible for bonus.")

"""# Create a program to check whether a given username and password match predefined credentials"""

username = input("Enter the username: ")
password = input("Enter the password: ")

if

"""# A traffic monitoring system needs to determine whether a vehicle exceeded the speed limit"""

speed = int(input("Enter the speed of vehicle: "))

if speed >= 40:
  print("Speed limit exceeded.")
else:
  print("Speed limit NOT exceeded.")